### ISSUE TITLE
here's some code that drives a neopixel LED chain stuck to my wall

### ISSUE THREAD

**Issue by benclifford** [unisonweb/share#3]
.spiral> pr.create git@github.com:unisonweb/share:.contrib.benclifford.spiral git@github.com:
                                                                   
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load git@github.com:unisonweb/share:.contrib.benclifford.spiral git@github.com:benclifford/unisoncode:.spiral
  
  Added definitions:
  
     Beat.beat   : Nat ->{Beat} ()
     beater      : Request Beat a ->{IO, Exception} a
     beaterTimed : Int -> Request Beat a ->{IO, Exception} a
     Beat.doc    : Doc
     drive       : Nat
                 -> (Nat ->{IO, Exception} [(Nat, Nat, Nat)])
                 ->{IO, Exception, Beat} ()
     gamma       : Float -> Float
     pattern1    : Nat -> [(Nat, Nat, Nat)]

**Comment by hojberg** [comment]
merged
